spring:
  application:
    name: ReverseGanttChart
  datasource:
    url: jdbc:postgresql://localhost:54321/storage
    password: password
    driver-class-name: org.postgresql.Driver
    username: user

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: password
      timeout: 2000ms

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
        debug: true

jwt:
  cookie-token-key: '{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'
logging:
  level:
    by.pirog.ReverseGanttChart: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG


app:
  frontend-url: http://localhost:8080
  email:
    from: pirojochek01@gmail.com

  security:
    token:
      blacklist-token-project-ttl: 2d
      blacklist-token-project-prefix: "blacklist:project:"
      blacklist-token-auth-ttl: 7d
      blacklist-token-auth-prefix: "blacklist:auth:"
    cookie:
      project-cookie-name: "project-token"
      auth-cookie-name: "auth-token"
