version: "3"

services:
  postgres:
    image: postgres:16
    container_name: database_host
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=storage
    ports:
      - "54321:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis_cache_gantt
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:

